In [7]:
import pandas as pd
import numpy as np
students = [[89,'M','verygood'],[95,'F','excellent'],[75,None,'good'],[np.NaN,'M','average'],[71,'M','good'],[np.NaN, None,'verygood'],[96,'F','verygood'],[98,'M','excellent']]

dfstudents = pd.DataFrame(students)
dfstudents.columns = ['Marks', 'Gender','Result']
dfstudents

   Marks Gender     Result
0   89.0      M   verygood
1   95.0      F  excellent
2   75.0   None       good
3    NaN      M    average
4   71.0      M       good
5    NaN   None   verygood
6   96.0      F   verygood
7   98.0      M  excellent

In [8]:
dfstudents.isnull().values.sum()

4

In [9]:
import numpy as np

x = dfstudents.iloc[:, 0:2].values
y = dfstudents.iloc[:, 2].values

print(x)
print(y)

[[89.0 'M']
 [95.0 'F']
 [75.0 None]
 [nan 'M']
 [71.0 'M']
 [nan None]
 [96.0 'F']
 [98.0 'M']]
['verygood' 'excellent' 'good' 'average' 'good' 'verygood' 'verygood'
 'excellent']

In [10]:
from sklearn.impute import SimpleImputer
import numpy as np

imputer_x = SimpleImputer(missing_values=np.NaN, strategy='median')
x[:, 0:1] = imputer_x.fit_transform(x[:, 0:1])

imputer_df = SimpleImputer(missing_values=None, strategy='most_frequent')
dfstudents['Gender'] = imputer_df.fit_transform(dfstudents['Gender'].values.reshape(-1, 1))[:, 0]

print("Corrected DataFrame:")
print(dfstudents)

Corrected DataFrame:
   Marks Gender     Result
0   89.0      M   verygood
1   95.0      F  excellent
2   75.0      M       good
3    NaN      M    average
4   71.0      M       good
5    NaN      M   verygood
6   96.0      F   verygood
7   98.0      M  excellent

In [11]:
import pandas as pd
file_path = 'CountryAgeSalary.csv'
dfsal = pd.read_csv(file_path)
print("Original DataFrame:")
print(dfsal)

from sklearn.impute import SimpleImputer

imputer_age = SimpleImputer(missing_values=np.NaN, strategy='median')
dfsal['Age'] = imputer_age.fit_transform(dfsal['Age'].values.reshape(-1, 1))

imputer_salary = SimpleImputer(missing_values=np.NaN, strategy='median')
dfsal['Salary'] = imputer_salary.fit_transform(dfsal['Salary'].values.reshape(-1, 1))

print("\nCorrected DataFrame:")
print(dfsal)

Original DataFrame:
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Corrected DataFrame:
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes